# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.1
    hooks:
      - id: markdownlint
      - id: markdownlint-fix
  #  - repo: https://github.com/thibaudcolas/pre-commit-stylelint
  #    rev: v14.5.3
  #    hooks:
  #      - id: stylelint
  #  - repo: https://github.com/pre-commit/mirrors-jshint
  #    rev: v2.13.4
  #    hooks:
  #      - id: jshint
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.11.0
    hooks:
      - id: eslint
        files: \.[jt]sx?$
        types: [file]
        additional_dependencies:
          - eslint@latest
          - eslint-config-standard@latest
          - babel-eslint@latest
          - eslint-config-prettier
          - eslint-plugin-prettier
