name = "zw"
type = "javascript"
workers_dev = false
routes = ["z.digitalclouds.dev", "z.digitalclouds.dev/zw/*", "z.digitalclouds.dev/img/*", "z.digitalclouds.dev/assets/*", "z.digitalclouds.dev/ja", "z.digitalclouds.dev/ja/zw/*", "z.digitalclouds.dev/ja/img/*", "z.digitalclouds.dev/ja/assets/*", "z.digitalclouds.dev/ru", "z.digitalclouds.dev/ru/zw/*", "z.digitalclouds.dev/ru/img/*", "z.digitalclouds.dev/ru/assets/*"]
zone_id = "7600c132f040aea60b0533ad801986d5"
account_id = "2db2112b269ed3616ed3a863a222f3e8"
usage_model = ''
site.bucket = "./build"
build.upload.main = "./functions"
compatibility_flags = []
compatibility_date = "2022-03-03"
triggers.crons = ["0 0 * JAN-JUN FRI", "0 0 LW JUL-DEC *"]
