/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "❮ ZI ❯",
  "tagline": "A Swiss Army Knife for Zsh Unix shell",
  "url": "https://z.digitalclouds.dev",
  "baseUrl": "/zh-Hans/",
  "titleDelimiter": "|",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "/zw/favicon.ico",
  "projectName": "zw",
  "organizationName": "z-shell",
  "staticDirectories": [
    "static"
  ],
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en",
      "ja",
      "ru",
      "zh-Hans"
    ],
    "localeConfigs": {}
  },
  "scripts": [
    {
      "src": "https://kit.fontawesome.com/a6c194e645.js",
      "crossorigin": "anonymous"
    },
    {
      "src": "https://enterprise.crowdin.com/crowdjet/crowdjet.js"
    }
  ],
  "plugins": [
    [
      "content-docs",
      {
        "id": "community",
        "path": "community",
        "routeBasePath": "community",
        "sidebarPath": "/home/sall/Codespace/zi_workspace/github/z-shell/zw/lib/js/sidebars_2.js"
      }
    ],
    [
      "pwa",
      {
        "debug": false,
        "offlineModeActivationStrategies": [
          "appInstalled",
          "standalone",
          "queryString"
        ],
        "pwaHead": [
          {
            "tagName": "link",
            "rel": "icon",
            "href": "/zw/logo.svg"
          },
          {
            "tagName": "link",
            "rel": "manifest",
            "href": "/manifest.json"
          },
          {
            "tagName": "link",
            "rel": "browserconfig",
            "href": "/browserconfig.xml"
          },
          {
            "tagName": "meta",
            "name": "theme-color",
            "content": "rgb(35, 184, 152)"
          },
          {
            "tagName": "meta",
            "name": "apple-mobile-web-app-capable",
            "content": "yes"
          },
          {
            "tagName": "meta",
            "name": "apple-mobile-web-app-status-bar-style",
            "content": "#000"
          },
          {
            "tagName": "link",
            "rel": "apple-touch-icon",
            "href": "/zw/logo.png"
          },
          {
            "tagName": "meta",
            "name": "msapplication-TileImage",
            "content": "/zw/logo.png"
          },
          {
            "tagName": "meta",
            "name": "msapplication-TileColor",
            "content": "#000"
          }
        ]
      }
    ],
    [
      "ideal-image",
      {
        "quality": 70,
        "max": 1030,
        "min": 640,
        "steps": 2,
        "disableInDev": false
      }
    ]
  ],
  "presets": [
    [
      "classic",
      {
        "debug": true,
        "docs": {
          "path": "docs",
          "routeBasePath": "docs",
          "breadcrumbs": true,
          "sidebarPath": "/home/sall/Codespace/zi_workspace/github/z-shell/zw/lib/js/sidebars_1.js",
          "showLastUpdateAuthor": true,
          "showLastUpdateTime": true,
          "disableVersioning": false,
          "includeCurrentVersion": true
        },
        "blog": {
          "showReadingTime": true
        },
        "pages": {},
        "theme": {
          "customCss": "/home/sall/Codespace/zi_workspace/github/z-shell/zw/src/css/custom.css"
        },
        "sitemap": {
          "changefreq": "weekly"
        },
        "gtag": {
          "trackingID": "G-MT10GVL59X",
          "anonymizeIP": true
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "zw/logo/320x320.png",
    "announcementBar": {
      "id": "announcemnt",
      "content": "If you like ❮ ZI ❯ - give it a <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://github.com/z-shell/zi\">⭐️</a> and follow us on <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://github.com/z-shell\"><i class=\"fa-brands fa-github-alt\" width=\"16\" height=\"16\">GitHub</i></a> or <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://twitter.com/zshell_zi\"><i class=\"fa-brands fa-twitter\" width=\"16\" height=\"16\">Twitter</i></a>",
      "isCloseable": true
    },
    "algolia": {
      "appId": "8A6CKETM6G",
      "apiKey": "1750c7420e10ff8acf4d4f1f7ca0de90",
      "indexName": "z-digitalclouds",
      "contextualSearch": true,
      "searchParameters": {},
      "searchPagePath": "search"
    },
    "metadata": [
      {
        "name": "twitter:card",
        "content": "summary"
      }
    ],
    "autoCollapseSidebarCategories": true,
    "hideableSidebar": true,
    "colorMode": {
      "defaultMode": "dark",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "navbar": {
      "hideOnScroll": true,
      "title": "❮ ZI ❯",
      "logo": {
        "alt": "❮ ZI ❯ Logo",
        "src": "zw/logo.svg",
        "target": "_self",
        "width": 32,
        "height": 32
      },
      "items": [
        {
          "type": "doc",
          "docId": "intro",
          "position": "left",
          "label": "Docs"
        },
        {
          "type": "localeDropdown",
          "position": "right",
          "dropdownItemsAfter": [
            {
              "href": "https://digitalclouds.crowdin.com/z-shell",
              "label": "Help Us Translate"
            }
          ],
          "dropdownItemsBefore": []
        },
        {
          "href": "https://github.com/z-shell/zi/",
          "position": "right",
          "className": "header-github-link",
          "aria-label": "GitHub repository"
        }
      ]
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "Introduction",
              "to": "/docs/intro"
            },
            {
              "label": "Community Docs",
              "to": "/community/intro"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "GitHub Discussions",
              "href": "https://github.com/z-shell/community/discussions"
            },
            {
              "label": "Matrix.org",
              "href": "https://matrix.to/#/#zi:matrix.org"
            },
            {
              "label": "Twitter.com",
              "href": "https://twitter.com/zshell_zi/"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "GitHub Organization",
              "href": "https://github.com/z-shell/"
            },
            {
              "label": "Crowdin Translations",
              "href": "https://digitalclouds.crowdin.com/z-shell/"
            },
            {
              "label": "Blog",
              "to": "/blog"
            }
          ]
        },
        {
          "title": "Legal",
          "items": [
            {
              "label": "Privacy Policy",
              "to": "legal/privacy_policy/"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2022 Digital Clouds, Z-Shell ❮ ZI ❯ Community."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": []
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 6
    },
    "docs": {
      "versionPersistence": "localStorage"
    }
  },
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "customFields": {},
  "themes": [],
  "stylesheets": [],
  "clientModules": [],
  "noIndex": false
};
