/*
AUTOGENERATED - DON'T EDIT
Your edits in this file will be overwritten in the next build!
Modify the docusaurus.config.js file at your site's root instead.
*/
export default {
  "title": "❮ ZI ❯",
  "titleDelimiter": "|",
  "tagline": "A Swiss Army Knife for Zsh - Unix shell",
  "url": "https://z-shell.pages.dev",
  "organizationName": "z-shell",
  "projectName": "zw",
  "trailingSlash": false,
  "baseUrl": "/ja/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "throw",
  "favicon": "img/favicon.svg",
  "staticDirectories": [
    "static"
  ],
  "themes": [],
  "plugins": [],
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en",
      "ja"
    ],
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "theme": {
          "customCss": "/workspaces/zw/src/css/custom.css"
        },
        "docs": {
          "sidebarPath": "/workspaces/zw/sidebars.js",
          "editUrl": "https://github.com/z-shell/zw/tree/main/",
          "editLocalizedFiles": true,
          "showLastUpdateTime": true,
          "showLastUpdateAuthor": true,
          "remarkPlugins": [
            null,
            [
              null,
              {
                "sync": true
              }
            ]
          ],
          "rehypePlugins": [
            null
          ]
        },
        "pages": {
          "remarkPlugins": [
            null,
            [
              null,
              {
                "sync": true
              }
            ]
          ],
          "rehypePlugins": [
            null
          ]
        },
        "blog": {
          "editUrl": "https://github.com/z-shell/zw/tree/main/",
          "editLocalizedFiles": true,
          "remarkPlugins": [
            null,
            [
              null,
              {
                "sync": true
              }
            ]
          ],
          "rehypePlugins": [
            null
          ],
          "blogTitle": "❮ ZI ❯ Blog",
          "blogDescription": "News, Changes & Updates",
          "postsPerPage": "ALL"
        },
        "sitemap": {
          "changefreq": "daily",
          "priority": 0.5
        },
        "gtag": {
          "trackingID": "G-46BGZ6PZR4",
          "anonymizeIP": true
        }
      }
    ]
  ],
  "themeConfig": {
    "announcementBar": {
      "id": "announcemnt",
      "content": "⭐️ If you like ❮ ZI ❯, give it a star on <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://github.com/z-shell/zi\">GitHub</a> and follow us on <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://twitter.com/zshell_zi\" >Twitter</a> <svg style=\"fill: #1DA1F2; vertical-align: middle;\" width=\"16\" height=\"16\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 512 512\"><path d=\"M459.37 151.716c.325 4.548.325 9.097.325 13.645 0 138.72-105.583 298.558-298.558 298.558-59.452 0-114.68-17.219-161.137-47.106 8.447.974 16.568 1.299 25.34 1.299 49.055 0 94.213-16.568 130.274-44.832-46.132-.975-84.792-31.188-98.112-72.772 6.498.974 12.995 1.624 19.818 1.624 9.421 0 18.843-1.3 27.614-3.573-48.081-9.747-84.143-51.98-84.143-102.985v-1.299c13.969 7.797 30.214 12.67 47.431 13.319-28.264-18.843-46.781-51.005-46.781-87.391 0-19.492 5.197-37.36 14.294-52.954 51.655 63.675 129.3 105.258 216.365 109.807-1.624-7.797-2.599-15.918-2.599-24.04 0-57.828 46.782-104.934 104.934-104.934 30.213 0 57.502 12.67 76.67 33.137 23.715-4.548 46.456-13.32 66.599-25.34-7.798 24.366-24.366 44.833-46.132 57.827 21.117-2.273 41.584-8.122 60.426-16.243-14.292 20.791-32.161 39.308-52.628 54.253z\"></path></svg>",
      "backgroundColor": "#193C47",
      "textColor": "#F5F6F7",
      "isCloseable": true
    },
    "image": "img/logo/501x501.png",
    "metadata": [
      {
        "name": "twitter:card",
        "content": "summary"
      }
    ],
    "hideableSidebar": false,
    "colorMode": {
      "defaultMode": "dark",
      "disableSwitch": false,
      "respectPrefersColorScheme": true,
      "switchConfig": {
        "darkIcon": "🌙",
        "lightIcon": "☀",
        "darkIconStyle": {
          "marginLeft": "1px"
        },
        "lightIconStyle": {
          "marginLeft": "1px"
        }
      }
    },
    "algolia": {
      "appId": "4FTAL4NR6O",
      "apiKey": "9ec9227571a8499464ac9389f1ab1616",
      "indexName": "dev-z-shell",
      "contextualSearch": true,
      "searchParameters": {}
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "defaultLanguage": "shell",
      "additionalLanguages": []
    },
    "liveCodeBlock": {
      "playgroundPosition": "bottom"
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 5
    },
    "navbar": {
      "hideOnScroll": true,
      "title": "❮ ZI ❯",
      "logo": {
        "alt": "ZI Logo",
        "src": "img/logo.svg",
        "width": 28,
        "height": 28
      },
      "items": [
        {
          "type": "doc",
          "docId": "intro",
          "position": "left",
          "label": "Wiki"
        },
        {
          "type": "localeDropdown",
          "position": "right",
          "dropdownItemsBefore": [],
          "dropdownItemsAfter": []
        },
        {
          "href": "https://github.com/z-shell/zi",
          "position": "right",
          "className": "header-github-link",
          "aria-label": "GitHub repository"
        }
      ]
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "Introduction",
              "to": "/docs/intro"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "Github Discussions",
              "href": "https://github.com/z-shell/zi/discussions"
            },
            {
              "label": "Discord",
              "href": "https://discord.gg/8W7yVpX9Hg"
            }
          ]
        },
        {
          "title": "Social",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/z-shell"
            },
            {
              "label": "Twitter",
              "href": "https://twitter.com/zshell_zi"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2022 Z-Shell ZI, Community."
    },
    "docs": {
      "versionPersistence": "localStorage"
    },
    "autoCollapseSidebarCategories": false
  },
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "customFields": {},
  "noIndex": false
};